"""empty message

Revision ID: 003e438b2c06
Revises: 0c9a0ff4db41
Create Date: 2024-08-07 14:16:27.052052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '003e438b2c06'
down_revision = '0c9a0ff4db41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
       "check_user_or_staff",
       "custom_sessions",
       "(user_id IS NOT NULL AND staff_id IS NULL) OR (user_id IS NULL AND staff_id IS NOT NULL)"
       )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_user_or_staff", "custom_sessions", type_='check')
    # ### end Alembic commands ###
