"""empty message

Revision ID: 12a3898cfa28
Revises: ed66e7cbe1b8
Create Date: 2024-07-17 16:42:37.169316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12a3898cfa28'
down_revision = 'ed66e7cbe1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

       email_template_table = sa.table('email_template',
              sa.column('id', sa.Integer()),
              sa.column('name', sa.String(255)),
              sa.column('subject', sa.String(255)),
              sa.column('body', sa.String(255)),
              sa.column('sender', sa.String(255)),
       )

       op.bulk_insert(email_template_table, [{'name': 'Payment Email', 'subject': 'Completed Payment Email', 'body': 'Hello you just bought: and the information about the order is : ','sender': 'galincho112@gmail.com'}])

    # ### end Alembic commands ###


def downgrade():
    pass
