"""empty message

Revision ID: 24b6648642a7
Revises: cd22e3aa087d
Create Date: 2024-07-19 14:03:34.214798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24b6648642a7'
down_revision = 'cd22e3aa087d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
       settings_table = sa.table('settings',
              sa.column('id', sa.Integer()),
              sa.column('name', sa.String(255)),
              sa.column('value', sa.String(255)),

       )

       op.bulk_insert(settings_table, [{'name': 'email_template_background_color', 'value': '#f2f2f2'}])
       op.bulk_insert(settings_table, [{'name': 'email_template_text_align', 'value': 'right'}])
       op.bulk_insert(settings_table, [{'name': 'email_template_border', 'value': '1'}])
       op.bulk_insert(settings_table, [{'name': 'email_template_border_collapse', 'value': 'collapse'}])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    pass

    # ### end Alembic commands ###
