"""empty message

Revision ID: 3d4845663f7a
Revises: 4fb4d7e50bdf
Create Date: 2024-07-16 11:49:34.173180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d4845663f7a'
down_revision = '4fb4d7e50bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    settings = op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    op.bulk_insert(settings, 
       [
              {
              'name': 'report_limitation_rows', 
              'value': 10001
              }
       ]

     )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('settings')

    # ### end Alembic commands ###
