"""empty message

Revision ID: 4fb4d7e50bdf
Revises: df0a40effd34
Create Date: 2024-07-09 15:34:51.310262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fb4d7e50bdf'
down_revision = 'df0a40effd34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    email_template_table = op.create_table('email_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(email_template_table, 
       [
              {
              'name': 'Verification Email', 
              'subject': 'Email Verification', 
              'body': 'Please insert the verification code in the form: ',
              'sender': 'galincho112@gmail.com'
              }
       ]

     )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('email_template')

    # ### end Alembic commands ###
