"""empty message

Revision ID: 59074f67cf33
Revises: d3b5a59a6796
Create Date: 2024-06-10 10:57:14.178422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59074f67cf33'
down_revision = 'd3b5a59a6796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_sessions',
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_sessions')
    # ### end Alembic commands ###
