"""empty message

Revision ID: 711aa5db185d
Revises: dc715d5be2ca
Create Date: 2024-06-18 09:45:36.440376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '711aa5db185d'
down_revision = 'dc715d5be2ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    conn = op.get_bind()

    # Check if the 'id' column already exists
    result = conn.execute(text("SELECT column_name FROM information_schema.columns WHERE table_name='custom_sessions' AND column_name='id'"))
    exists = result.fetchone()
    
    if not exists:
        # If the column does not exist, add it
        op.add_column('custom_sessions', sa.Column('id', sa.Integer, nullable=False))

    # Drop existing primary key constraint
    op.drop_constraint('custom_sessions_pkey', 'custom_sessions', type_='primary')

    # Add a new primary key to the 'id' column
    op.create_primary_key(None, 'custom_sessions', ['id'])

    op.create_unique_constraint(None, 'custom_sessions', ['session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, 'custom_sessions', type_='unique')
    op.drop_column('custom_sessions', 'id')

    op.create_primary_key('custom_sessions_pkey', 'custom_sessions', ['session_id'])

    # ### end Alembic commands ###
