"""empty message

Revision ID: 77ac3c54b36d
Revises: 4bf4c07f047e
Create Date: 2024-08-01 14:57:46.869843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77ac3c54b36d'
down_revision = '4bf4c07f047e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("DROP TABLE IF EXISTS settings CASCADE")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='settings_pkey'),
    sa.UniqueConstraint('name', name='settings_name_key')
    )

    op.create_foreign_key('products_vat_id_fkey', 'products', 'settings', ['vat_id'], ['id'])
    # ### end Alembic commands ###
