"""empty message

Revision ID: 802267659ea3
Revises: b039f0f99020
Create Date: 2024-08-01 14:24:33.273378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '802267659ea3'
down_revision = 'b039f0f99020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('custom_sessions', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('custom_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
