"""empty message

Revision ID: b039f0f99020
Revises: 24b6648642a7
Create Date: 2024-07-22 10:29:05.651536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b039f0f99020'
down_revision = '24b6648642a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    settings = sa.table('settings',
    sa.Column('id', sa.Integer()),
    sa.Column('name', sa.String(length=255)),
    sa.Column('value', sa.Integer()),
    )

    op.bulk_insert(settings, 
       [
              {
              'name': 'VAT', 
              'value': '20'
              }
       ]

     )

    # ### end Alembic commands ###

def downgrade():
       pass
