"""empty message

Revision ID: cb15bc2eb3ae
Revises: 28786c342b6c
Create Date: 2024-07-16 17:00:59.100381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb15bc2eb3ae'
down_revision = '28786c342b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('custom_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=True))
        
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'staff', ['staff_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   

    with op.batch_alter_table('custom_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

        batch_op.drop_column('staff_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
