"""empty message

Revision ID: d84a82e11c25
Revises: b1de21b89b46
Create Date: 2024-05-10 09:36:14.430798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd84a82e11c25'
down_revision = 'b1de21b89b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('name', sa.TEXT()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'name')
    # ### end Alembic commands ###
