"""empty message

Revision ID: dc715d5be2ca
Revises: 58d96fb77686
Create Date: 2024-06-17 12:06:57.454712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc715d5be2ca'
down_revision = '58d96fb77686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Define the currencies table structure
    currencies_table = sa.table('currencies',
        sa.column('id', sa.Integer()),
        sa.column('code', sa.String(10)),
        sa.column('name', sa.String(50)),
        sa.column('symbol', sa.String(10))
    )

    # Insert default data into the currencies table
    op.bulk_insert(currencies_table, [
        {'code': 'BGN', 'name': 'Bulgarian lev', 'symbol': 'лв'},
        {'code': 'USD', 'name': 'United States Dollar', 'symbol': '$'},
        {'code': 'EUR', 'name': 'Euro', 'symbol': '€'},
        {'code': 'GBP', 'name': 'British Pound', 'symbol': '£'}
    ])
    
    # Set default currency_id for existing products
    op.execute('UPDATE products SET currency_id = (SELECT id FROM currencies WHERE code = \'BGN\')')
    
    # Set the currency_id column to not nullable
    op.alter_column('products', 'currency_id', existing_type=sa.Integer(), nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.execute('DELETE FROM currencies WHERE id > 0')
    # ### end Alembic commands ###