"""empty message

Revision ID: df0a40effd34
Revises: 711aa5db185d
Create Date: 2024-06-19 15:24:01.010353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df0a40effd34'
down_revision = '711aa5db185d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('custom_sessions', schema=None) as batch_op:
       batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('custom_sessions', schema=None) as batch_op:
       batch_op.drop_column('is_active')

    # ### end Alembic commands ###
