"""empty message

Revision ID: e5c30a0e385d
Revises: 6294dc04f327
Create Date: 2024-05-10 18:28:39.183491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5c30a0e385d'
down_revision = '6294dc04f327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country_codes') as batch_op:
        batch_op.create_unique_constraint(None, ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country_codes') as batch_op:
        batch_op.drop_constraint(None, type_='unique')
    # ### end Alembic commands ###
