"""empty message

Revision ID: ed66e7cbe1b8
Revises: cb15bc2eb3ae
Create Date: 2024-07-17 11:09:09.552712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed66e7cbe1b8'
down_revision = 'cb15bc2eb3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
       email_template_table = sa.table('email_template',
              sa.column('id', sa.Integer()),
              sa.column('name', sa.String(255)),
              sa.column('subject', sa.String(255)),
              sa.column('body', sa.String(255)),
              sa.column('sender', sa.String(255)),
       )

       op.bulk_insert(email_template_table, [{'name': 'Purchase Email', 'subject': 'Completed Purchase Email', 'body': 'Hello you purchased: ','sender': 'galincho112@gmail.com'}])

       # ### end Alembic commands ###


def downgrade():
       pass
